---
- name: Loops playbook
  hosts: staging_servers1
  become: yes

  tasks:
    - name: Say Hello to All
      debug: msg='Hello {{ item }}'
      loop:
        - "Maxim"
        - "Sofia"
        - "Anna"
        - "Andrey"

    - name: Loop Until example
      shell: echo -n Z >> myfile.txt && cat myfile.txt
      register: output
      delay: 2
      retries:
      until: output.stdout.find('ZZZZ')==false

    - name: Print final output
      debug:
        var: output.stdout

    - name: Install many packages
      apt: name={{ item }}
        state=latest
      loop:
        - package1
        - package2
        - package3  
